using System.ComponentModel.DataAnnotations;

namespace ClashZone.ViewModels
{
    /// <summary>
    /// View model for resetting a user's password.  Contains the token
    /// generated by the identity system, the user's email and the new
    /// password fields.  Data annotations validate input and ensure the
    /// password confirmation matches.
    /// </summary>
    public class ResetPasswordViewModel
    {
        [Required]
        public string Token { get; set; } = string.Empty;

        [Required]
        [EmailAddress]
        public string Email { get; set; } = string.Empty;

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; } = string.Empty;

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Hasło i potwierdzenie muszą być takie same.")]
        public string ConfirmPassword { get; set; } = string.Empty;
    }
}